
camera_info_publisher:
  ros__parameters:
    Camera/fx: 457.734101
    Camera/fy: 457.546052
    Camera/cx: 325.450360
    Camera/cy: 239.276712

    Camera/k1: -0.034416
    Camera/k2: 0.068476
    Camera/p1: 0.004233
    Camera/p2: -0.005272

    Camera/width: 640
    Camera/height: 480

image_publisher_left:
  ros__parameters:
    framerate: 20
    sensor_id: 1
    topic: /camera/left/image_raw
    frame_id: /camera_link

image_publisher_right:
  ros__parameters:
    framerate: 20
    sensor_id: 0
    topic: /camera/right/image_raw
    frame_id: /camera_link_right